Tern Project file is not saved after a plug-in is added
When configuring an existing Tern Project and we have to add some plug-in to that project,
it's not marked as a 'dirty' project, so the new .tern-project file is not saved.
As result the newly added plugin is not working (in Content Assist and validation) and the
following exceptions appear in the error log:

!ENTRY org.eclipse.angularjs.core 4 0 2014-09-18 00:45:29.697
!MESSAGE Error while tern validator.
!STACK 0
tern.TernException: tern.TernException: No query type 'angular' defined
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:315)
	at tern.eclipse.ide.core.IDETernProject.request(IDETernProject.java:729)
	at tern.eclipse.ide.core.IDETernProject.request(IDETernProject.java:710)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.isAngularElementExists(ValidatorUtils.java:244)
	at org.eclipse.angularjs.core.validation.ValidatorUtils.validate(ValidatorUtils.java:188)
	at org.eclipse.angularjs.ui.validation.HTMLAngularContentValidator.doValidate(HTMLAngularContentValidator.java:26)
	at org.eclipse.angularjs.internal.ui.validation.AbstractValidator.validate(AbstractValidator.java:152)
	at org.eclipse.angularjs.internal.ui.validation.AbstractValidator.validate(AbstractValidator.java:134)
	at org.eclipse.angularjs.internal.ui.validation.AbstractValidator.validate(AbstractValidator.java:118)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.validate(ReconcileStepForValidator.java:381)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ReconcileStepForValidator.reconcileModel(ReconcileStepForValidator.java:259)
	at org.eclipse.jface.text.reconciler.AbstractReconcileStep.reconcile(AbstractReconcileStep.java:95)
	at org.eclipse.wst.sse.ui.internal.reconcile.validator.ValidatorStrategy.reconcile(ValidatorStrategy.java:269)
	at org.eclipse.wst.sse.ui.internal.reconcile.DocumentRegionProcessor.process(DocumentRegionProcessor.java:321)
	at org.eclipse.wst.sse.ui.internal.reconcile.StructuredRegionProcessor.process(StructuredRegionProcessor.java:258)
	at org.eclipse.wst.sse.ui.internal.reconcile.DirtyRegionProcessor$BackgroundThread.run(DirtyRegionProcessor.java:691)
Caused by: tern.TernException: No query type 'angular' defined
	at tern.server.nodejs.NodejsTernHelper.makeRequest(NodejsTernHelper.java:87)
	at tern.server.nodejs.NodejsTernServer.makeRequest(NodejsTernServer.java:170)
	at tern.server.nodejs.NodejsTernServer.request(NodejsTernServer.java:301)
	... 15 more

Signed-off-by: vrubezhny <vrubezhny@exadel.com>